apiVersion: v1
kind: Pod
metadata:
  name: optract
  labels:
    app: optract-reader
spec:
  containers:
    - name: optract-reader
      image: infwonder/optract-reader
      ports:
        - containerPort: 45054
          name: pubsub
        - containerPort: 59437
          name: websocket
---
apiVersion: v1
kind: Service
metadata:
  name: optract-service
spec:
  selector:
    app: optract-reader
  type: NodePort
  ports:
    - name: pubsub
      protocol: TCP
      port: 45054
      targetPort: pubsub
    - name: websocket
      protocol: TCP
      port: 59437
      targetPort: websocket
