#!/bin/bash

OD=`pwd`;
MO=$1;

rm -f ${OD}/Optract.LOCK;

if [ ${MO:-daemon} == "console" ]; then
   exec $OD/bin/node $OD/lib/console.js;
elif [ ${MO:-daemon} == "devConsole" ]; then
  sed "s|__OPTRACT_INSTALL__|${OD}|g" ./dapps/config.json.dist > ./dapps/config.json && \
  rm -fr ${OD}/node_modules && ${OD}/bin/asar extract ${OD}/node_modules.asar ${OD}/node_modules && \
  echo -e "!!!!!\nNOTE: devConsole requires you turn off wsrpc in config.json ...\n!!!!!" && \
  $OD/bin/node $OD/lib/console.js;
  exit 0;
elif [ ${MO:-daemon} == "daemon" ]; then
  sed "s|__OPTRACT_INSTALL__|${OD}|g" ./dapps/config.json.dist > ./dapps/config.json && \
  rm -fr ${OD}/node_modules && ${OD}/bin/asar extract ${OD}/node_modules.asar ${OD}/node_modules && \
  ${OD}/bin/node ${OD}/lib/daemon.js;
  exit 0;
fi
